gitea:
  url: http://127.0.0.1:3000
  token: ${GITEA_TOKEN}

logs:
  max-log-history: 10
  level: deploy

hooks:
  on-agent-start: "echo agent-start：${hook_current_time}"

scripts:
  reload-nginx-cmd: "nginx -s reload"

services:

  - name: frontend
    package:
      type: generic
      owner: OwnerName
      name: PackageName
      file: dist.zip
    deploy:
      strategy: frontend-dist
      target: /data/nginx/web/my-website

  - name: docker-compose-backend
    package:
      type: docker-container
      owner: OwnerName
      name: PackageName
    deploy:
      strategy: docker-compose
      compose: /data/docker/compose/my-backend-1/docker-compose.yml
      service: backend
      started-check-seconds: 3
